### ISSUE TITLE
Modify eosio.token to enable us to reduce max supply

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/telos.contracts#33]
## Overview

Modify eosio.token to enable us to reduce max supply. This needs to be prioritized as it's part of the TEDP3 plan that has been approved.  The new supply will be 1billion instead of 10billion.

## Acceptance criteria

- max supply should be reduceable

## Technical considerations

- The action doesn't need to receive any parameters because it'll be used only once
- Deploy the branch with the change, execute the task. We don't want to add this action to the main branch, but keep in a branch specific for executing this action.
- Protect the branch from branches swipes
- The main branch will be deployed after the action is executed

## Tasks

- [x] Modify eosio.token contract to add an action that allows the max supply in the stat table to be reduced.  It would also be acceptable to have the new supply hardcoded to be 1billion since this is a one time action.
- [ ] Deploy modified contract on testnet and test this action, then re-deploy the previous version without the action to modify max supply (work with @poplexity to do the testnet deployments).
- [ ] Do the same process on mainnet via msig (@poplexity will handle this)
