### ISSUE TITLE
3.1 system code updates

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/telos.contracts#36]
## Overview

These changes originated from a code review executed in a call with @poplexity and @guilledk.

## Acceptance criteria

- Apart from our custom Telos changes, all other contract code should be from upstream
- Test auto kick
- BPs from missed blocks
- Test standby rotation
- Test the distribution contract
- Ensure on block is succeeding and `block_num` is increasing
- Check that inversed weighted voting is being applied
- Ensure BP pay is flat and active receives double the amount of standby BPs
- Test general REX functionality (even with return pools ❓ )
- Normal and timed multisig (thanks to Ryan J from Teleology)

## Tasks

- [ ] Review the telos.contracts repo for optimal change set: the minimum amount of code changes needed
- [x] List the minimum changes in this issue as tasks
- [x] Produce another file like [TELOS-CHANGES.md](https://github.com/guilledk/telos-system-contracts/blob/telos-specific/TELOS-CHANGES.md), but with less custom changes
- [x] Investigate return pools and if they affect the REX functionality
- [x] Deployment to stagenet and testing
- [x] Deployment to testnet and testing

**Comment by guilledk** [comment]
Here is an interesting commit https://github.com/AntelopeIO/reference-contracts/commit/f98a2336b101b507e86da37678b3a67950aa123b to analyze the rex return pools machinery
